routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DropdownController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\UsersController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\admin\ProductController;
use App\Http\Controllers\admin\CategoryController;
use App\Http\Controllers\Auth\ChangePasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// Google login
Route::get('login/google', [LoginController::class, 'redirectToGoogle'])->name('login.google');
Route::get('login/google/callback', [LoginController::class, 'handleGoogleCallback']);

// Github login
Route::get('login/github', [LoginController::class, 'redirectToGithub'])->name('login.github');
Route::get('login/github/callback', [LoginController::class, 'handleGithubCallback']);

/* User Dashboard */
Route::get('/home', [HomeController::class, 'index'])->name('home');

/* Admin Dashboard */
Route::get('admin/home', [HomeController::class, 'adminHome'])->name('adminhome');

/* Fetch City From States Using AJAX */
Route::post('fetch-cities', [DropdownController::class, 'fetchCity']);

/* LogOut */
Route::get('/logout', [LogoutController::class, 'logout'])->name('logout');

/* My profile */
Route::get('myprofile', [UsersController::class, 'myProfile'])->name('myprofile');
Route::post('updatemyprofile', [UsersController::class, 'updateMyProfile'])->name('updatemyprofile');

/* Change Password */
Route::get('/changePassword', [ChangePasswordController::class, 'showChangePasswordGet'])->name('changePasswordGet');
Route::post('/changePassword', [ChangePasswordController::class, 'changePasswordPost'])->name('changePasswordPost');

/* Fetch Records Using AJAX */
Route::get('/fetchrecord', [HomeController::class, 'fetchrecords'])->name('fetchrecords');

/* Add To Cart */
Route::get('add-to-cart/{id}', [HomeController::class, 'addToCart'])->name('add.to.cart');

/* View Cart */
Route::get('cart', [HomeController::class, 'cart'])->name('cart');

/* Update Cart */
Route::patch('update-cart', [HomeController::class, 'update'])->name('update.cart');

/* Delete Cart */
Route::delete('remove-from-cart', [HomeController::class, 'remove'])->name('remove.from.cart');

Route::middleware(['is_admin'])->group(function () {
    Route::group(['prefix' => 'admin'], function () {

        /* Category Section */
        Route::resource('category', CategoryController::class);

        /* Product Section */
        Route::resource('product', ProductController::class);
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\Product;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Category extends Model
{
    use HasFactory, SoftDeletes;
    protected $table = 'categories';
    protected $primaryKey = 'id';
    protected $fillable = [
        'name',
        'status',
    ];

    public function product()
    {
        return $this->hasMany(Product::class, 'category_id', 'id')->where('status',config('const.statusActiveInt'));
    }

    public static function addEditCategory($request, $id = '')
    {

        if ($id != '') {
            $data = Category::find($id);
        } else {
            $data = new Category();
        }
        $data->name = $request->name;
        $data->status = isset($request->status) ? $request->status : config('const.statusActiveInt');

        $data->save();
        return $data;
    }

    public static function getCategoryDetails($id)
    {
        $data = Category::find($id);
        return $data;
    }
}

app/Http/Controllers/admin/CategoryController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::all();
        return view('admin.category.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try
        {
            $rules = array(
                'name' => 'required',
                'status' => 'required',
            );

            $validator = Validator::make($request->all(), $rules);
            if ($validator->fails()) {
                return back()->withInput()->withErrors($validator->errors());
            }
            DB::beginTransaction();
            Category::addEditCategory($request);
            DB::commit();
            session()->flash('success', trans('admin.categorycreatesuccess'));
            return redirect()->route('category.index');

        } catch (\Exception $e) {
            DB::rollBack();
            session()->flash('error', $e->getMessage());
            return redirect()->route('category.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $data = Category::getCategoryDetails($id);
            return view('admin.category.show', compact('data'));
        } catch (\Exception $e) {
            session()->flash('error', $e->getMessage());
            return redirect()->route('category.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $data = Category::getCategoryDetails($id);
            return view('admin.category.edit', compact('data'));
        } catch (\Exception $e) {
            session()->flash('error', $e->getMessage());
            return redirect()->route('category.edit', $id);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $rules = array(
                'name' => 'required',
                'status' => 'required',
            );

            $validator = Validator::make($request->all(), $rules);
            if ($validator->fails()) {
                return back()->withInput()->withErrors($validator->errors());
            }

            DB::beginTransaction();
            Category::addEditCategory($request, $id);
            DB::commit();

            session()->flash('success', trans('admin.categoryupdatesuccess'));
            return redirect()->route('category.index');
        } catch (\Exception $e) {
            DB::rollBack();
            session()->flash('error', $e->getMessage());
            return back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $data = Category::where('id', $id)->delete();
            return Response::json(["status" => true,"message" => "Record deleted successfully."]);
        } catch (\Exception $e) {
            return Response::json($e);
        }
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.master')
@section('title', 'Category Create')
@section('content')

    <!-- Horizontal Form -->
    <br>
    <section class="content">
        <div class="container-fluid">

            <div class="col-md-6">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Category Information</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action="{{ route('category.store') }}" id="category_form" method="post">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" id="name" name="name" class="form-control"
                                    placeholder="Enter Category Name" required>
                            </div>
                            <div class="form-group">
                                <label>Status</label>
                                <select class="form-control select2bs4" name="status" id="v"
                                    data-placeholder="Select Status" style="width: 100%;">
                                    <option disabled selected value="">-- Select Status --</option>
                                    <option value="0">Inactive</option>
                                    <option value="1">Active</option>
                                </select>
                            </div>
                            <!-- /.card -->
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info">Save</button>
                                <a href="{{ route('category.index') }}"><button type="button"
                                        class="btn btn-secondary cancelbutton">Cancel</button></a>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- /.card -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#category_form").validate({
                rules: {
                    name: {
                        required: true,
                    },
                    status: {
                        required: true,
                    },
                },
                errorElement: 'span',
                errorPlacement: function(error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function(element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function(element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        });
    </script>

@endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.master')
@section('title', 'Category Update')
@section('content')

    <!-- Horizontal Form -->
    <br>
    <section class="content">
        <div class="container-fluid">

            <div class="col-md-6">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Update Category Information</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action="{{ route('category.update', $data['id']) }}" id="category_form" method="post">
                        {{csrf_field()}}
                        {{ method_field('PUT')}}
                        <div class="card-body">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" id="name" name="name" value="{{$data->name}}" class="form-control"
                                    placeholder="Enter Category Name" required>
                            </div>
                            <div class="form-group">
                                <label>Status</label>
                                <select class="form-control select2bs4" name="status" id="v"
                                    data-placeholder="Select Status" style="width: 100%;">
                                    <option disabled selected value="">-- Select Status --</option>
                                    <option {{ ($data->status) == '0' ? 'selected' : '' }} value="0">Inactive</option>
                                    <option {{ ($data->status) == '1' ? 'selected' : '' }} value="1">Active</option>
                                </select>
                            </div>
                            <!-- /.card -->
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info">Update</button>
                                <a href="{{ route('category.index') }}"><button type="button"
                                        class="btn btn-secondary cancelbutton">Cancel</button></a>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- /.card -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#category_form").validate({
                rules: {
                    name: {
                        required: true,
                    },
                    status: {
                        required: true,
                    },
                },
                errorElement: 'span',
                errorPlacement: function(error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function(element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function(element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        });
    </script>

@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.master')
@section('title', 'AdminLTE | Category Info')
@section('content')

    <!-- BEGIN: Content-->
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Add Category</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <a href="{{ route('category.create') }}">
                <button type="button" style="width: 100px" class="btn btn-block btn-outline-primary">Add</button>
            </a>
            <br>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Category Information</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            @if (Session::has('message'))
                                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">
                                    {{ Session::get('message') }}</p>
                            @endif
                            <table id="example2" class="table table-bordered table-hover">
                                <thead align="center">
                                    <tr>
                                        <th>ID</th>
                                        <th>Category Name</th>
                                        <th>Status</th>
                                        <th>Date</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody align="center">
                                    @foreach ($category as $data)
                                        <tr id="row-{{ $data->id }}">
                                            <td>{{ $data->id }}</td>
                                            <td>{{ $data->name }}</td>
                                            @if ($data->status == '0')
                                                <td>Inactive</td>
                                            @else
                                                <td>Active</td>
                                            @endif
                                            <td>{{ $data->created_at->format('d/m/Y') }}</td>
                                            <td>
                                                <a href="{{ route('category.show', $data->id) }}" data-toggle="tooltip"
                                                    data-placement="bottom" title="Show"><i class="fas fa-eye"
                                                        aria-hidden="true"></i></a> &nbsp;&nbsp;&nbsp;&nbsp;
                                                <a href="{{ route('category.edit', $data->id) }}" data-toggle="tooltip"
                                                    data-placement="bottom" title="Update"><i class="fas fa-edit"
                                                        aria-hidden="true"></i></a> &nbsp;&nbsp;&nbsp;&nbsp;
                                                <a href="javascript:void(0)" id="{{ $data->id }}" class="dlt"
                                                    data-toggle="tooltip" data-placement="bottom" title="Delete">
                                                    <i class="fas fa-trash" aria-hidden="true"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- END: Content-->
@endsection

@section('pagejs')
    <script>
        $(document).ready(function() {
            $('[data-toggle="tooltip"]').tooltip();
            var table;

            var initTable1 = function() {
                table = $('#example2');
                table.DataTable({
                    "responsive": true,
                    "lengthChange": true,
                    "autoWidth": true,
                    "paging": true,
                    "searching": true,
                    "ordering": true,
                    "info": true,
                    "columnDefs": [{
                        width: 100,
                        targets: 4
                    }],
                    "fixedColumns": true,
                    "pageLength": 5,
                });
            };

            $(document).on("click", ".dlt", function() {
                var id = $(this).attr("id")
                // alert(id);
                Swal.fire({
                    text: '{{ trans('admin.deleteSure') }}',
                    icon: "warning",
                    showCancelButton: !0,
                    buttonsStyling: !1,
                    confirmButtonText: "Yes, delete!",
                    cancelButtonText: "No, cancel",
                    customClass: {
                        confirmButton: "btn fw-bold btn-danger",
                        cancelButton: "btn fw-bold btn-active-dark-primary"
                    }
                }).then(function(isConfirm) {
                    if (isConfirm.value) {
                        $.ajaxSetup({
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            }
                        });
                        $.ajax({
                            url: baseUrl + '/admin/category/' + id,
                            type: "DELETE",
                            dataType: 'json',
                            success: function(data) {
                                if (data == 'Error') {
                                    toastr.error("@lang('admin.oopserror')",
                                        "@lang('admin.error')");
                                } else {
                                    toastr.success('@lang('admin.recordDelete')',
                                        '@lang('admin.success')');
                                    // $('#example2').DataTable().reload();
                                    $('#row-' + id).remove();
                                }
                            },
                            error: function(data) {
                                toastr.error("@lang('admin.oopserror')",
                                    "@lang('admin.error')");
                            }
                        });
                    }
                })
            });
        });
    </script>
@endsection

resources/views/admin/category/show.blade.php
@extends('layouts.master')
@section('title', 'Category View')
@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Category Information</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <a href="{{ route('category.index') }}"><button type="button"
                            style="float: right" class="btn btn-secondary cancelbutton">Back</button></a>
                        <dl class="row">
                            <dt class="col-3">Category Name</dt>
                            <dd class="col-9">
                                <p>{{ $data->name }}</p>
                            </dd>

                            <dt class="col-3">Status</dt>
                            <dd class="col-9">
                                @if ($data->status == '0')
                                    Inactive
                                @else
                                    Active
                                @endif
                            </dd>
                        </dl>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

@endsection