routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DropdownController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\UsersController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\admin\ProductController;
use App\Http\Controllers\admin\CategoryController;
use App\Http\Controllers\Auth\ChangePasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// Google login
Route::get('login/google', [LoginController::class, 'redirectToGoogle'])->name('login.google');
Route::get('login/google/callback', [LoginController::class, 'handleGoogleCallback']);

// Github login
Route::get('login/github', [LoginController::class, 'redirectToGithub'])->name('login.github');
Route::get('login/github/callback', [LoginController::class, 'handleGithubCallback']);

/* User Dashboard */
Route::get('/home', [HomeController::class, 'index'])->name('home');

/* Admin Dashboard */
Route::get('admin/home', [HomeController::class, 'adminHome'])->name('adminhome');

/* Fetch City From States Using AJAX */
Route::post('fetch-cities', [DropdownController::class, 'fetchCity']);

/* LogOut */
Route::get('/logout', [LogoutController::class, 'logout'])->name('logout');

/* My profile */
Route::get('myprofile', [UsersController::class, 'myProfile'])->name('myprofile');
Route::post('updatemyprofile', [UsersController::class, 'updateMyProfile'])->name('updatemyprofile');

/* Change Password */
Route::get('/changePassword', [ChangePasswordController::class, 'showChangePasswordGet'])->name('changePasswordGet');
Route::post('/changePassword', [ChangePasswordController::class, 'changePasswordPost'])->name('changePasswordPost');

/* Fetch Records Using AJAX */
Route::get('/fetchrecord', [HomeController::class, 'fetchrecords'])->name('fetchrecords');

/* Add To Cart */
Route::get('add-to-cart/{id}', [HomeController::class, 'addToCart'])->name('add.to.cart');

/* View Cart */
Route::get('cart', [HomeController::class, 'cart'])->name('cart');

/* Update Cart */
Route::patch('update-cart', [HomeController::class, 'update'])->name('update.cart');

/* Delete Cart */
Route::delete('remove-from-cart', [HomeController::class, 'remove'])->name('remove.from.cart');

Route::middleware(['is_admin'])->group(function () {
    Route::group(['prefix' => 'admin'], function () {

        /* Category Section */
        Route::resource('category', CategoryController::class);

        /* Product Section */
        Route::resource('product', ProductController::class);
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use App\Models\Category;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'products';
    protected $primaryKey = 'id';
    protected $fillable = [
        'name',
        'status',
    ];

    public function category()
    {
        return $this->hasOne(Category::class, 'id', 'category_id');
    }

    public static function addEditProduct($request, $id = '')
    {
        if ($id != '') {
            $data = Product::find($id);            
        } else {
            $data = new Product();
        }
        $data->category_id = $request->category_id;
        $data->name = $request->name;
        $data->description = $request->description;

        if (isset($request->image) && $request->image != '') {
            /* Unlink Image */
            if (isset($data->image) && $data->image != '') {
                $imagePath = 'images/Product_images/' . '' . $data->image;
                if (file_exists($imagePath)) {
                    unlink($imagePath);
                }
            }
            $image = $request->image;
            $imageName = 'Product-' . time() . '.' . $request->image->getClientOriginalExtension();
            $image->move('images/Product_images/', $imageName);
            $data->image = $imageName;
        }

        $data->price = $request->price;
        $data->discount = $request->discount;
        $data->stock = $request->stock;
        $data->status = isset($request->status) ? $request->status : config('const.statusActiveInt');

        $data->save();
        return $data;
    }

    public static function getProductDetails($id)
    {
        $data = Product::find($id);
        return $data;
    }
}

app/Http/Controllers/admin/ProductController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Validator;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = Product::all();
        return view('admin.product.index', compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        return view('admin.product.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try
        {
            $rules = array(
                'name' => 'required',
                'status' => 'required',
            );

            $validator = Validator::make($request->all(), $rules);
            if ($validator->fails()) {
                return back()->withInput()->withErrors($validator->errors());
            }
            DB::beginTransaction();
            Product::addEditProduct($request);
            DB::commit();
            session()->flash('success', trans('admin.productcreatesuccess'));
            return redirect()->route('product.index');

        } catch (\Exception $e) {
            DB::rollBack();
            session()->flash('error', $e->getMessage());
            return redirect()->route('product.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $data = Product::getProductDetails($id);
            return view('admin.product.show', compact('data'));
        } catch (\Exception $e) {
            session()->flash('error', $e->getMessage());
            return redirect()->route('product.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $data = Product::find($id);
            // dd($data);
            $category = Category::all();
            return view('admin.product.edit', compact('data', 'category'));
        } catch (\Exception $e) {
            session()->flash('error', $e->getMessage());
            return redirect()->route('product.edit', $id);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $rules = array(
                'name' => 'required',
                'status' => 'required',
            );

            $validator = Validator::make($request->all(), $rules);
            if ($validator->fails()) {
                return back()->withInput()->withErrors($validator->errors());
            }

            DB::beginTransaction();
            Product::addEditProduct($request, $id);
            DB::commit();

            session()->flash('success', trans('admin.productupdatesuccess'));
            return redirect()->route('product.index');
        } catch (\Exception $e) {
            DB::rollBack();
            session()->flash('error', $e->getMessage());
            return back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $data = Product::where('id', $id)->delete();
            return Response::json(["status" => true, "message" => "Record deleted successfully."]);
        } catch (\Exception $e) {
            return Response::json($e);
        }
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.master')
@section('title', 'Product Create')
@section('content')

    <!-- Horizontal Form -->
    <br>
    <section class="content">
        <div class="container-fluid">

            <div class="col-md-6">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Product Information</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action="{{ route('product.store') }}" id="product_form" method="post"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label>Product Category<span class="required">*</span></label>
                                <select class="form-control select2bs4" name="category_id" id="category_id"
                                    data-placeholder="Select Category" style="width: 100%;">
                                    <option disabled selected value="">-- Select Status --</option>
                                    @foreach ($category as $data)
                                        <option value="{{ $data->id }}">{{ $data->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Product Name<span class="required">*</span></label>
                                <input type="text" id="name" name="name" class="form-control"
                                    placeholder="Enter Product Name" required>
                            </div>

                            <div class="form-group">
                                <label>Product Description<span class="required">*</span></label>
                                <textarea class="form-control" id="description" name="description" placeholder="Enter Product Description " rows="3"></textarea>
                            </div>

                            <div class="form-group">
                                <label for="image">Product Image<span class="required">*</span></label>
                                <div class="custom-file">
                                    <input type="file" class="form-control custom-file-input" id="image" name="image"
                                        accept="image/*">
                                    <label class="custom-file-label" for="image">Choose file</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label>Product Price<span class="required">*</span></label>
                                <input type="number" id="price" name="price" class="form-control"
                                    placeholder="Enter Product Price" required>
                            </div>

                            <div class="form-group">
                                <label>Product Discount<span class="required">*</span></label>
                                <input type="number" id="discount" name="discount" class="form-control"
                                    placeholder="Enter Product Discount" required>
                            </div>

                            <div class="form-group">
                                <label>Product Stock<span class="required">*</span></label>
                                <input type="number" id="stock" name="stock" class="form-control"
                                    placeholder="Enter Product Stock" required>
                            </div>

                            <div class="form-group">
                                <label>Status<span class="required">*</span></label>
                                <select class="form-control select2bs4" name="status" id="status"
                                    data-placeholder="Select Status" style="width: 100%;">
                                    <option disabled selected value="">-- Select Status --</option>
                                    <option value="0">Inactive</option>
                                    <option value="1">Active</option>
                                </select>
                            </div>
                            <!-- /.card -->
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info">Save</button>
                                <a href="{{ route('product.index') }}"><button type="button"
                                        class="btn btn-secondary cancelbutton">Cancel</button></a>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- /.card -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#product_form").validate({
                rules: {
                    category_id: {
                        required: true,
                    },
                    name: {
                        required: true,
                    },
                    description: {
                        required: true,
                    },
                    image: {
                        required: true,
                        extension: "jpg|jpeg|png"
                    },
                    price: {
                        required: true,
                    },
                    discount: {
                        required: true,
                    },
                    stock: {
                        required: true,
                    },
                    status: {
                        required: true,
                    },
                },
                messages: {
                    image: {
                        required: "Please upload product image.",
                        extension: "The image must be a file of type: jpg, jpeg, png."
                    }
                },
                errorElement: 'span',
                errorPlacement: function(error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function(element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function(element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        });
    </script>

@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.master')
@section('title', 'Product Update')
@section('content')

    <!-- Horizontal Form -->
    <br>
    <section class="content">
        <div class="container-fluid">

            <div class="col-md-6">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Update Product Information</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    {{-- {{ dd($data) }} --}}
                    <form action="{{ route('product.update', $data->id) }}" id="product_form" method="post"
                        enctype="multipart/form-data">
                        @csrf
                        {{ method_field('PUT') }}
                        <div class="card-body">
                            <div class="form-group">
                                <label>Product Category<span class="required">*</span></label>
                                <select class="form-control select2bs4" name="category_id" id="category_id"
                                    data-placeholder="Select Category" style="width: 100%;">
                                    @foreach ($category as $row)
                                        <option {{ $data->category_id == $row->id ? 'selected' : '' }}
                                            value="{{ $row->id }}">
                                            {{ $row->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Product Name<span class="required">*</span></label>
                                <input type="text" id="name" name="name" value="{{ $data->name }}" class="form-control"
                                    placeholder="Enter Product Name" required>
                            </div>

                            <div class="form-group">
                                <label>Product Description<span class="required">*</span></label>
                                <textarea class="form-control" id="description" name="description" placeholder="Enter Product Description " rows="3">{{ $data->description }}</textarea>
                            </div>

                            <div class="form-group">
                                <label for="image">Product Image<span class="required">*</span></label>
                                <div class="custom-file">
                                    <input type="file" class="form-control custom-file-input" id="image" name="image"
                                        accept="image/*">
                                    <label class="custom-file-label" for="image">{{ $data->image }}</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label>Product Price<span class="required">*</span></label>
                                <input type="number" id="price" name="price" class="form-control"
                                    value="{{ $data->price }}" placeholder="Enter Product Price" required>
                            </div>

                            <div class="form-group">
                                <label>Product Discount<span class="required">*</span></label>
                                <input type="number" id="discount" name="discount" class="form-control"
                                    value="{{ $data->discount }}" placeholder="Enter Product Discount" required>
                            </div>

                            <div class="form-group">
                                <label>Product Stock<span class="required">*</span></label>
                                <input type="number" id="stock" name="stock" class="form-control"
                                    value="{{ $data->stock }}" placeholder="Enter Product Stock" required>
                            </div>

                            <div class="form-group">
                                <label>Status<span class="required">*</span></label>
                                <select class="form-control select2bs4" name="status" id="status"
                                    data-placeholder="Select Status" style="width: 100%;">
                                    <option disabled selected value="">-- Select Status --</option>
                                    <option {{ $data->status == '0' ? 'selected' : '' }} value="0">Inactive</option>
                                    <option {{ $data->status == '1' ? 'selected' : '' }} value="1">Active</option>
                                </select>
                            </div>
                            <!-- /.card -->
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info">Update</button>
                                <a href="{{ route('product.index') }}"><button type="button"
                                        class="btn btn-secondary cancelbutton">Cancel</button></a>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- /.card -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#product_form").validate({
                rules: {
                    category_id: {
                        required: true,
                    },
                    name: {
                        required: true,
                    },
                    description: {
                        required: true,
                    },
                    image: {
                        extension: "jpg|jpeg|png"
                    },
                    price: {
                        required: true,
                    },
                    discount: {
                        required: true,
                    },
                    stock: {
                        required: true,
                    },
                    status: {
                        required: true,
                    },
                },
                messages: {
                    image: {
                        extension: "The image must be a file of type: jpg, jpeg, png."
                    }
                },
                errorElement: 'span',
                errorPlacement: function(error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function(element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function(element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        });
    </script>

@endsection

resources/views/admin/product/show.blade.php
@extends('layouts.master')
@section('title', 'Product View')
@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Product Information</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <a href="{{ route('product.index') }}"><button type="button" style="float: right"
                                class="btn btn-secondary cancelbutton">Back</button></a>
                        <dl class="row">

                            <dt class="col-3">Category Name</dt>
                            <dd class="col-9">
                                <p>{{ $data->category->name }}</p>
                            </dd>

                            <dt class="col-3">Name</dt>
                            <dd class="col-9">
                                <p>{{ $data->name }}</p>
                            </dd>

                            <dt class="col-3">Description</dt>
                            <dd class="col-9">
                                <p>{{ $data->description }}</p>
                            </dd>

                            <dt class="col-3">Image</dt>
                            <dd class="col-9">
                                <p><img src="{{ asset('images/Product_images/' . $data->image) }}" width="50px"
                                        height="50px" class="img-circle"
                                        onerror="this.onerror=null;this.src='{{ asset('storage/images/default/no_image.png') }}';">
                                </p>
                            </dd>

                            <dt class="col-3">Price</dt>
                            <dd class="col-9">
                                <p>{{ $data->price }}</p>
                            </dd>

                            <dt class="col-3">Discount</dt>
                            <dd class="col-9">
                                <p>{{ $data->discount }}</p>
                            </dd>

                            <dt class="col-3">Stock</dt>
                            <dd class="col-9">
                                <p>{{ $data->stock }}</p>
                            </dd>

                            <dt class="col-3">Status</dt>
                            <dd class="col-9">
                                @if ($data->status == '0')
                                    Inactive
                                @else
                                    Active
                                @endif
                            </dd>

                        </dl>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

@endsection